
import java.awt.Dimension;
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 8282r
 */
public class JumpTests extends javax.swing.JFrame {
    public static BasePanel currentPanel = null;
    public static TitlePanel titlePanel;
    public static JumpPanel jumpPanel;
    private static JumpTests instance;
    public static JumpTests getInstance(){
        if(instance == null)
            instance = new JumpTests();
        return instance;
    }

    public JumpTests() {
        initComponents();
        System.out.println(WIDTH);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int)screenSize.getWidth();
        int height = (int)screenSize.getHeight();
        this.setResizable(false);
        this.setBounds(width/2 - 720/2, height/2 - 490/2, 720, 490);
        titlePanel = new TitlePanel(this);
        jumpPanel = new JumpPanel(this);
        currentPanel = titlePanel;
    }
    
    public static enum STATE {GAME,TITLE,QUIT};
    public void setState(JumpTests.STATE _State) {
        System.out.println("        STATE : " + _State);
        currentPanel.setRunnale(false);
        getContentPane().removeAll();        
        switch(_State) {
            case GAME :
                currentPanel = jumpPanel;
                break;
            case TITLE :
                currentPanel = titlePanel;
                break;
            case QUIT :
                System.exit(1);
                break;
        }
        System.out.println("        currentPanel : " + currentPanel);
        setContentPane(currentPanel);
        currentPanel.requestFocus();       
        currentPanel.setRunnale(true);
        validate();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(720, 490));
        setMinimumSize(new java.awt.Dimension(720, 490));
        setPreferredSize(new java.awt.Dimension(720, 490));
        setSize(new java.awt.Dimension(720, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JumpTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JumpTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JumpTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JumpTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JumpTests obj = new JumpTests();
                obj.setState(STATE.TITLE);
                obj.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
